name: FFmpeg with libfdk-aac for Termux

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Android NDK
        uses: nttld/setup-ndk@main
        with:
          ndk-version: r25c

      - name: Install build tools
        run: |
          sudo apt update
          sudo apt install -y build-essential git autoconf automake libtool pkg-config

      - name: Set environment variables
        run: |
          echo "TOOLCHAIN=$ANDROID_NDK/toolchains/llvm/prebuilt/linux-x86_64" >> $GITHUB_ENV
          echo "TARGET=aarch64-linux-android" >> $GITHUB_ENV
          echo "API=21" >> $GITHUB_ENV
          echo "PREFIX=$HOME/ffmpeg-out" >> $GITHUB_ENV

      - name: Build libfdk-aac
        run: |
          export TOOLCHAIN=$ANDROID_NDK/toolchains/llvm/prebuilt/linux-x86_64
          export TARGET=aarch64-linux-android
          export API=21
          export CC=$TOOLCHAIN/bin/${TARGET}${API}-clang
          export CXX=$TOOLCHAIN/bin/${TARGET}${API}-clang++
          export AR=$TOOLCHAIN/bin/llvm-ar
          export LD=$TOOLCHAIN/bin/ld
          export STRIP=$TOOLCHAIN/bin/llvm-strip

          git clone https://github.com/mstorsjo/fdk-aac.git
          cd fdk-aac
          autoreconf -fiv
          ./configure --host=$TARGET --prefix=$HOME/fdk-aac-build --disable-shared --enable-static
          make -j$(nproc)
          make install

      - name: Download and build FFmpeg
        run: |
          wget https://ffmpeg.org/releases/ffmpeg-7.1.1.tar.bz2
          tar xjf ffmpeg-7.1.1.tar.bz2
          cd ffmpeg-7.1.1

          export TOOLCHAIN=$ANDROID_NDK/toolchains/llvm/prebuilt/linux-x86_64
          export TARGET=aarch64-linux-android
          export API=21
          export PREFIX=$HOME/ffmpeg-out
          export CC=$TOOLCHAIN/bin/${TARGET}${API}-clang
          export CXX=$TOOLCHAIN/bin/${TARGET}${API}-clang++
          export AR=$TOOLCHAIN/bin/llvm-ar
          export LD=$TOOLCHAIN/bin/ld
          export STRIP=$TOOLCHAIN/bin/llvm-strip

          ./configure \
            --prefix=$PREFIX \
            --target-os=android \
            --arch=aarch64 \
            --cross-prefix=$TOOLCHAIN/bin/${TARGET}- \
            --sysroot=$TOOLCHAIN/sysroot \
            --cc=$CC \
            --cxx=$CXX \
            --ar=$AR \
            --strip=$STRIP \
            --enable-cross-compile \
            --enable-gpl \
            --enable-nonfree \
            --enable-libfdk-aac \
            --extra-cflags="-I$HOME/fdk-aac-build/include" \
            --extra-ldflags="-L$HOME/fdk-aac-build/lib" \
            --disable-static \
            --enable-shared

          make -j$(nproc)
          make install

      - name: Upload FFmpeg binary
        uses: actions/upload-artifact@v4
        with:
          name: ffmpeg-libfdk-aac-termux
          path: $HOME/ffmpeg-out
