name: Compile FFmpeg for Termux

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-ffmpeg:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Android NDK
        uses: nttld/setup-ndk@main
        with:
          ndk-version: r25c

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y git autoconf automake libtool pkg-config nasm yasm

      - name: Download FFmpeg source code
        run: |
          wget -O ffmpeg.tar.bz2 https://www.ffmpeg.org/releases/ffmpeg-7.1.1.tar.bz2
          tar -xjf ffmpeg.tar.bz2
          mv ffmpeg-7.1.1 ffmpeg

      - name: Build libfdk-aac for Termux
        run: |
          git clone https://github.com/mstorsjo/fdk-aac.git
          cd fdk-aac
          ./autogen.sh
          ./configure --host=aarch64-linux-android --prefix=$HOME/libfdk-aac-android
          make -j$(nproc)
          make install

      - name: Build FFmpeg for Termux
        run: |
          cd ffmpeg
          export PATH="$PATH:$ANDROID_NDK/toolchains/llvm/prebuilt/linux-x86_64/bin"
          export SYSROOT="$ANDROID_NDK/toolchains/llvm/prebuilt/linux-x86_64/sysroot"
          export CC="aarch64-linux-android-clang"
          export CXX="aarch64-linux-android-clang++"
          export AR="llvm-ar"
          export NM="llvm-nm"
          export STRIP="llvm-strip"

          ./configure \
            --prefix=$HOME/ffmpeg-android \
            --arch=aarch64 \
            --target-os=android \
            --cross-prefix=aarch64-linux-android- \
            --sysroot=$SYSROOT \
            --enable-cross-compile \
            --enable-gpl \
            --enable-libass \
            --enable-libfreetype \
            --enable-libfribidi \
            --enable-libmp3lame \
            --enable-libopus \
            --enable-libtheora \
            --enable-libvorbis \
            --enable-libvpx \
            --enable-libx264 \
            --enable-libx265 \
            --enable-libfdk-aac \
            --enable-nonfree

          make -j$(nproc)
          make install
