name: Daily Visit

on:
  workflow_dispatch:  # 手动触发
  schedule:
    - cron: '0 16 * * *'  # 每天UTC时间16:00（北京时间00:00）

jobs:
  visit-website:
    runs-on: ubuntu-latest
    steps:
      - name: Visit Website
        run: |
          response=$(curl -s -L -o /dev/null -w "%{url_effective}\n" https://downloads.khinsider.com/?u=2980544)
          echo "Final URL: $response"
